name = "droid-apikey"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "key"
database_id = "794d112d-f339-4dfe-83e0-3a6df24bd4b2"

# 环境变量
[vars]
EXPORT_PASSWORD = "zhaoweihao98"  # 导出密码，建议修改

# 开发环境配置
[env.dev]
[[env.dev.d1_databases]]
binding = "DB"
database_name = "key"
database_id = "794d112d-f339-4dfe-83e0-3a6df24bd4b2"